[package]
name = "bench-map"
version = "0.1.0"
edition = "2024"

[dependencies]
concread = "0"
dashmap = "6"
starshard = "2"
txmap = "2"

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }
rand = "0.10.2"

[[bench]]
name = "concurrent_get"
harness = false

[[bench]]
name = "concurrent_insert"
harness = false

[[bench]]
name = "concurrent_insert_get_remove"
harness = false

[[bench]]
name = "get"
harness = false

[[bench]]
name = "insert"
harness = false

[[bench]]
name = "insert_get_remove"
harness = false
