[package]
name = "bench-map"
version = "1.0.0"
edition = "2024"

[dependencies]
ahash = "0"
concread = "0"
criterion = { version = "0.8.2", features = ["async_futures", "html_reports"] }
dashmap = "6"
fluxmap = "0"
hashbrown = "0"
immutable-chunkmap = "2"
indexmap = "2"
libc = "0"
rand = "0.10.2"
rustc-hash = "2"
starshard = "2"
txmap = "2"
uuid = { version = "1.24.0", features = ["v4"] }

[[bench]]
name = "baseline_insert"
harness = false

[[bench]]
name = "baseline_iterate"
harness = false

[[bench]]
name = "baseline_lookup_hit"
harness = false

[[bench]]
name = "baseline_lookup_miss"
harness = false

[[bench]]
name = "baseline_remove"
harness = false

[[bench]]
name = "key_sensitivity"
harness = false

[[bench]]
name = "concurrency"
harness = false

[[bench]]
name = "mixed_read_write"
harness = false
