[package]
name = "bench-map"
version = "1.0.0"
edition = "2024"

[dependencies]
concread = "0"
criterion = { version = "0.8.2", features = ["async_futures", "html_reports"] }
dashmap = "6"
fluxmap = "0"
hashbrown = "0"
immutable-chunkmap = "2"
starshard = "2"
txmap = "2"

[[bench]]
name = "concurrent_get"
harness = false

[[bench]]
name = "concurrent_insert"
harness = false

[[bench]]
name = "concurrent_insert_get_remove"
harness = false

[[bench]]
name = "get"
harness = false

[[bench]]
name = "insert"
harness = false

[[bench]]
name = "insert_get_remove"
harness = false
