name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update dependencies
        run: cargo update

      - name: Run benchmarks
        run: cargo bench

      - name: Copy redirect
        run: cp redirect.html target/criterion/index.html

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './target/criterion'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
